baseURL = "https://heen.dev/"
title = "Erik Heen"
languageCode = "en-us"
theme = "PaperMod"
copyright = "© 2022 Erik Heen •"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
baseURL = "https://heen.dev/"
title = "Erik Heen"
languageCode = "en-us"
theme = "PaperMod"
copyright = "© 2023"
relativeURLs = true
env = "production"
description = "Personal blog of Erik Heen. Student, music maker, nerd. BA CSci @ UMN-TC 2023."
#keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Erik Heen"
images = [ "img/selfie.jpg" ]
DateFormat = "2006 Jan 2"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showToc = false
tocopen = false

  [params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "ico/favicon16.png"
  favicon32x32 = "ico/favicon32.png"
  apple_touch_icon = "ico/appleTouchIcon.png"

  [params.label]
  text = "Erik Heen"
  icon = "ico/appleTouchIcon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Erik Heen"
  subtitle = "BA CSci @ UMN-TC, Class of 2023"
#  description = "Interested in UI / UX design semantics, video game UI & HUD design, Android, and user psychology. Songwriter, music producer, photographer, esports enthusiast, mental health advocate."
  imageUrl = "img/selfie.jpg"
  imageWidth = 240
  imageHeight = 240
  imageTitle = "Selfie"

#    [[params.profileMode.buttons]]
#    name = "Blog"
#    url = "blog"

#    [[params.profileMode.buttons]]
#    name = "Timeline"
#    url = "archive"

#    [[params.profileMode.buttons]]
#    name = "Projects"
#    url = "project"

#    [[params.profileMode.buttons]]
#    name = "Writeups"
#    url = "writeup"

#    [[params.profileMode.buttons]]
#    name = "Music"
#    url = "music"

  [params.homeInfoParams]
  Title = "Erik Heen"
  Content = ""

########## SOCIAL ICONS ############

# [[params.socialIcons]]
# name = "  "
# url = "  "

  [[params.socialIcons]]
  name = "email"
  url = "mailto:erik@heen.dev"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/eaheen"

  # [[params.socialIcons]]
  # name = "gitlab"
  # url = "https://gitlab.com/eaheen"

  # [[params.socialIcons]]
  # name = "bitbucket"
  # url = "https://bitbucket.org/eaheen"

  # [[params.socialIcons]]
  # name = "codepen"
  # url = "https://codepen.io/eaheen"

  # [[params.socialIcons]]
  # name = "cryptohack"
  # url = "https://cryptohack.org/user/eaheen/"

  # [[params.socialIcons]]
  # name = "leetcode"
  # url = "https://leetcode.com/eaheen/"

  # [[params.socialIcons]]
  # name = "stackoverflow"
  # url = "https://stackoverflow.com/users/15165192/eaheen"

  # [[params.socialIcons]]
  # name = "dev"
  # url = "https://dev.to/eaheen"

  # [[params.socialIcons]]
  # name = "reddit"
  # url = "https://reddit.com/u/eaheen"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/eaheen"

  # [[params.socialIcons]]
  # name = "hackerrank"
  # url = "https://hackerrank.com/eaheen"
  
  # [[params.socialIcons]]
  # name = "medium"
  # url = "https://medium.com/@eaheen"

  # [[params.socialIcons]]
  # name = "kofi"
  # url = "https://ko-fi.com/eaheen"

  # [[params.socialIcons]]
  # name = "twitter"
  # url = "https://twitter.com/eaheen"

  # [[params.socialIcons]]
  # name = "mastodon"
  # url = "https://hachyderm.io/@eaheen"

  # [[params.socialIcons]]
  # name = "instagram"
  # url = "https://instagram.com/eaheen"

  # [[params.socialIcons]]
  # name = "discord"
  # url = "https://discordapp.com/users/793779247831449621"

  # [[params.socialIcons]]
  # name = "soundcloud"
  # url = "https://soundcloud.com/eaheen"

  # [[params.socialIcons]]
  # name = "spotify"
  # url = "https://open.spotify.com/user/13lckr"

  [[params.socialIcons]]
  name = "signal"
  url = "signal"

  [[params.socialIcons]]
  name = "lastfm"
  url = "https://last.fm/user/eaheen"

  # [params.analytics.google]
  # SiteVerificationTag = "???"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

#  [params.editPost]
#  URL = "https://github.com/m9ple/blog"
#  Text = "View Source"
#  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

#[[menu.main]]
#identifier = "archive"
#name = "Timeline"
#url = "archive"
#weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "post"
weight = 11

#[[menu.main]]
#identifier = "writeup"
#name = "Writeups"
#url = "writeup"
#weight = 12

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "project"
weight = 13

#[[menu.main]]
#identifier = "music"
#name = "Music"
#url = "music"
#weight = 14

#[[menu.main]]
#identifier = "search"
#name = "Search"
#url = "search"
#weight = 30

[outputs]
home = ["HTML","RSS","JSON"]