baseURL = "https://heen.dev/"
title = "August Heen"
languageCode = "en-us"
theme = "PaperMod"
#copyright = "© 2024 August Heen •"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"

custom_css = ["css/main.css"]

[minify]
disableXML = true
minifyOutput = true

[params]
baseURL = "https://heen.dev/"
title = "August Heen"
languageCode = "en-us"
theme = "PaperMod"
copyright = "© 2024"
relativeURLs = true
env = "production"
description = "Personal blog of August Heen. Software engineer, music maker, nerd. BA CSci @ UMN-TC 2023."
#keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "August Heen"
images = [ "img/selfie.jpg" ]
DateFormat = "2006 Jan 2"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showToc = false
tocopen = false

  [params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "ico/favicon16.png"
  favicon32x32 = "ico/favicon32.png"
  apple_touch_icon = "ico/appleTouchIcon.png"

  [params.label]
  text = "August Heen"
  icon = "ico/appleTouchIcon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "August Heen"
  subtitle = ""
  description = "Engineer, music maker, nerd."
  imageUrl = "img/griggs.jpg"
  imageWidth = 240
  imageHeight = 240
  imageTitle = "Something Comforting, Griggs"

#    [[params.profileMode.buttons]]
#    name = "Blog"
#    url = "blog"

#    [[params.profileMode.buttons]]
#    name = "Timeline"
#    url = "archive"

#    [[params.profileMode.buttons]]
#    name = "Projects"
#    url = "project"

#    [[params.profileMode.buttons]]
#    name = "Writings"
#    url = "writing"

#    [[params.profileMode.buttons]]
#    name = "Music"
#    url = "music"

  [params.homeInfoParams]
  Title = "August Heen"
  Content = ""

########## SOCIAL ICONS ############

# [[params.socialIcons]]
# name = "  "
# url = "  "

  [[params.socialIcons]]
  name = "email"
  url = "mailto:<35fjatorl@mozmail.com>"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/aaheen"

  [[params.socialIcons]]
  name = "signal"
  url = "signal"

  [[params.socialIcons]]
  name = "lastfm"
  url = "https://last.fm/user/eaheen"

  # [params.analytics.google]
  # SiteVerificationTag = "???"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

#  [params.editPost]
#  URL = "https://github.com/aaheen/blog"
#  Text = "View Source"
#  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

#[[menu.main]]
#identifier = "archive"
#name = "Timeline"
#url = "archive"
#weight = 8

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "resume.pdf"
weight = 10

#[[menu.main]]
#identifier = "blog"
#name = "Blog"
#url = "post"
#weight = 12

#[[menu.main]]
#identifier = "writeup"
#name = "Writeups"
#url = "writeup"
#weight = 16

#[[menu.main]]
#identifier = "projects"
#name = "Projects"
#url = "project"
#weight = 20

#[[menu.main]]
#identifier = "music"
#name = "Music"
#url = "music"
#weight = 24

#[[menu.main]]
#identifier = "search"
#name = "Search"
#url = "search"
#weight = 28

[outputs]
home = ["HTML","RSS","JSON"]
