baseURL = "https://heen.dev/"
title = "Erik Heen"
languageCode = "en-us"
theme = "PaperMod"
copyright = "© 2022"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
# buildExpired = false
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
baseURL = "https://heen.dev/"
title = "Erik Heen"
languageCode = "en-us"
theme = "PaperMod"
copyright = "© 2022"
relativeURLs = true
env = "production"
description = "A simple showcase of who I am."
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Erik Heen"
# images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "2006 Jan 2"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showToc = false
tocopen = false

  [params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "ico/favicon16.png"
  favicon32x32 = "ico/favicon32.png"
  apple_touch_icon = "ico/appleTouchIcon.png"

  [params.label]
  text = "Erik Heen"
  icon = "ico/appleTouchIcon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Erik Heen"
  subtitle = "Student & UI/UX Developer"
  imageUrl = "img/selfie.jpg"
  imageWidth = 240
  imageHeight = 240
  imageTitle = "Selfie"

    [[params.profileMode.buttons]]
    name = "Blog"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "projects"

#    [[params.profileMode.buttons]]
#    name = "Music"
#    url = "music"

  [params.homeInfoParams]
  Title = "Erik Heen"
  Content = "A UI/UX developer in progress"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:erik@heen.dev"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/m9ple"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/eaheen"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/eaheen/"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.social/@m9ple"
  
  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/erik-heen-b238a8177"

#[[params.socialIcons]]
#name = "stackoverflow"
#url = "https://stackoverflow.com/users/15165192/m9ple"

#[params.analytics.google]
#SiteVerificationTag = "???"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/m9ple/blog"
  Text = "View Source"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "About"
url = "/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 30

#[[menu.main]]
#identifier = "music"
#name = "Music"
#url = "/music"
#weight = 40